<div class="alert alert-dismissable ajax" style="display: none;">
	<button type="button" class="close" onclick="$('.alert').hide()">&times;</button>
	<p></p>
</div>

<div class="center-form">
	<label class="control-label">Lot ID:</label> <input class="form-control" id="auc_id" type="text" placeholder="Enter lot ID"><br />
	<label class="control-label">Price:</label> <input class="form-control" id="price" type="text" placeholder="Enter wishful price"><br />
	<button id="form-bid" class="btn btn-primary ladda-button" data-style="zoom-in"><span class="ladda-label">Bid</span></button>
</div>


<div class="jumbotron">
	<?= Uri::create('controller', [], array('redirect' => 'paid')); ?><br />
	<?= Date::forge(strtotime('-1 minutes')) ?><br />
	<?= strtotime('-1 month') ?>

	<p>This admin panel has been generated by the FuelPHP Framework.</p>
	<p><a class="btn btn-primary btn-lg" href="http://docs.fuelphp.com">Read the Docs</a></p>
</div>
