branch-defaults:
  pack:
    environment: Sample-env
environment-defaults:
  Sample-env:
    branch: null
    repository: null
global:
  application_name: yahooauc
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-1::platform/PHP 7.0 running
    on 64bit Amazon Linux/2.4.0
  default_region: ap-northeast-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
files:
  "/etc/httpd/conf.d/virtualhost.conf":
    mode: "000644"
    owner: "root"
    group: "root"
    content: |
      NameVirtualHost *:80
      <VirtualHost *:80>
        DocumentRoot /var/www/html/public
        <Directory "/var/www/html/public">
          Allow from all
        </Directory>
      </VirtualHost>
